# Generated by Django 6.0.6 on 2026-07-02 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_api', '0002_weatherreading_cloud_cover_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_temperature', models.FloatField()),
                ('predicted_precipitation', models.FloatField()),
                ('model_used', models.CharField(default='LinearRegression+RandomForest', max_length=100)),
                ('predicted_at', models.DateTimeField(auto_now_add=True)),
                ('input_reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='data_api.weatherreading')),
            ],
        ),
    ]
