# Generated by Django 6.0.6 on 2026-07-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('temperature', models.FloatField()),
                ('feels_like', models.FloatField()),
                ('humidity', models.FloatField()),
                ('pressure', models.FloatField()),
                ('weather_desc', models.CharField(max_length=100)),
                ('wind_speed', models.FloatField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
