# Generated by Django 6.0.6 on 2026-07-02 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherreading',
            name='cloud_cover',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='weatherreading',
            name='precipitation',
            field=models.FloatField(default=0.0),
        ),
    ]
